# Bootstrap: crea repo en Azure DevOps (si no existe) y sincroniza desde GitHub
trigger: none
pr: none
pool:
  vmImage: ubuntu-latest

variables:
  ADO_REPO: 'exite'   # nombre del repositorio destino en Azure Repos
  GITHUB_URL: 'https://github.com/Yeison1994s/hotfix-lab-demo.git'  # origen

steps:
- checkout: none

# 1) Crear repo en Azure si no existe (usa la org/proyecto reales del pipeline)
- task: Bash@3
  displayName: Ensure Azure Repo exists
  inputs:
    targetType: inline
    script: |
      set -euo pipefail
      org="$(System.CollectionUri)"          # ej: https://dev.azure.com/mi-org/
      proj="$(System.TeamProject)"           # proyecto real donde corre el pipeline
      repo="$(ADO_REPO)"

      base="${org}${proj}/_apis/git/repositories?api-version=7.0"
      get="${org}${proj}/_apis/git/repositories/${repo}?api-version=7.0"

      b64=$(printf ':%s' "$(System.AccessToken)" | base64 -w0)

      echo "DEBUG org=${org} proj=${proj} repo=${repo}"
      if curl -fsS -H "Authorization: Basic $b64" "$get" >/dev/null; then
        echo "Repo ${repo} ya existe"
      else
        echo "Creando repo ${repo}"
        curl -fsS -X POST \
          -H "Authorization: Basic $b64" \
          -H "Content-Type: application/json" \
          --data "{\"name\":\"${repo}\"}" \
          "$base"
        echo "Repo creado"
      fi

# 2) Importar si vacío; si no, mirror desde GitHub
- task: Bash@3
  displayName: Import or mirror from GitHub
  inputs:
    targetType: inline
    script: |
      set -euo pipefail
      org="$(System.CollectionUri)"
      proj="$(System.TeamProject)"
      repo="$(ADO_REPO)"
      gh_url="$(GITHUB_URL)"

      ado_http="${org}${proj}/_git/${repo}"
      ado_git_auth="https://user:$(System.AccessToken)@${ado_http#https://}"

      # ¿Repo Azure vacío?
      if [ -z "$(git ls-remote --heads "$ado_git_auth" 2>/dev/null)" ]; then
        echo "Azure repo vacío → Import API"
        b64=$(printf ':%s' "$(System.AccessToken)" | base64 -w0)
        api="${org}${proj}/_apis/git/repositories/${repo}/importRequests?api-version=7.0"

        # Si GitHub es privado y defines GITHUB_PAT en Variables (secreto), se usa; si es público, no hace falta
        if [ -n "${GITHUB_PAT:-}" ]; then
          gh_url_auth="https://${GITHUB_PAT}@${gh_url#https://}"
        else
          gh_url_auth="$gh_url"
        fi

        curl -fsS -X POST \
          -H "Authorization: Basic $b64" \
          -H "Content-Type: application/json" \
          --data "{\"parameters\":{\"gitSource\":{\"url\":\"${gh_url_auth}\"}}}" \
          "$api"
        echo "Import solicitado"
      else
        echo "Azure repo con contenido → mirror push"
        work="$(mktemp -d)"; cd "$work"
        if [ -n "${GITHUB_PAT:-}" ]; then
          gh_url="https://${GITHUB_PAT}@${gh_url#https://}"
        fi
        git clone --mirror "$gh_url" mirror.git
        cd mirror.git
        git remote set-url --push origin "$ado_git_auth"
        git push --mirror
        echo "Mirror completado"
      fi
  env:
    GITHUB_PAT: $(GITHUB_PAT)   # opcional, solo si tu GitHub es privado
