trigger: none
pr: none
pool:
  vmImage: ubuntu-latest

steps:
- task: PowerShell@2
  displayName: Detectar/crear ramas y generar YAML final
  inputs:
    targetType: filePath
    filePath: init-branches.ps1
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
