trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

steps:
- task: PowerShell@2
  displayName: Detectar rama principal, crear developer/QA y generar YAML final
  inputs:
    targetType: filePath
    filePath: init-branches.ps1

- task: PublishPipelineArtifact@1
  displayName: Publicar YAML generado
  inputs:
    targetPath: '$(Build.SourcesDirectory)/azure-pipelines.generated.yml'
    artifact: 'pipeline-config'
    publishLocation: 'pipeline'
